version: "3.3"
services:
    web: 
        image: nginx:stable-alpine
        restart: always
        volumes:
            - ./default.conf:/etc/nginx/conf.d/default.conf
            - ../certbot/conf:/etc/nginx/ssl
            - ../certbot/data:/var/www/certbot
        ports:
            - 80:80
            - 443:443

    certbot:
        image: certbot/certbot:latest
        command: certonly --webroot --webroot-path=/var/www/certbot --email mail@domain.com --agree-tos --no-eff-email -d domain.com -d www.domain.com
        volumes:
            - ../certbot/conf:/etc/letsencrypt
            - ../certbot/logs:/var/log/letsencrypt
            - ../certbot/data:/var/www/certbot